### ISSUE TITLE
[Suggestion] Add feature to encode and decode chat messages in multiple ciphers

### ISSUE THREAD

**Issue by DarkReaper231** [BleachDrinker420/BleachHack#296]
Make it possible to encode outcoming messages in like base64, caesar, enigma, hash, rail fence, hex, binary and many more and also decode incoming messages. Then two players could just enable this and communicate in ciphers. Would also be nice if it could detect some basic ciphers. For example base64 is possible to detect. Same for caesar, hex, binary and some well known hash algorithms.

**Comment by BleachDrinker420** [comment]
all of these are either just different encodings of the same message (which would probably need to be cut off because the encoded message would be much longer than the chat can handle) or very easily guessable ciphers even without a decryption key, the current encryption is designed to be basically impossible to decrypt without both the key & message.

**Comment by DarkReaper231** [comment]
Fair enough
